title : "Visual Studio Extension Development 2019"
name  : "Sungchool Park"
lang: ko
description: "Visual Studio Extension Development 2019"

url     : "https://grimhang.github.io"
baseurl : "/SQLServerQueryPerformanceTuning"


#theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme
# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
